### ISSUE TITLE
how to check strong consistency of TiDB

### ISSUE THREAD

**Issue by thinhdanggroup** [pingcap/chaos#33]
Currently, I am using your tool to check strong consistency of TiDB. But, when I set too many request-count to have enough time to run chaos, **porcupine** will out of memory because it doesn't work with too many events. 

Can you give me any solution to check strong consistency of TiDB with chaos?

Besides, I propose that we can run continuously test ( about 200 events logs per test) and use porcupine to check them. If all tests passed, the database would be strong consistency. Is that true?

**Comment by siddontang** [comment]
PTAL @overvenus 

seem we have already supported rolling history so we can let porcupine just checks some events every time, right?

**Comment by siddontang** [comment]
@thinhdanggroup 

> Besides, I propose that we can run continuously test ( about 200 events logs per test) and use porcupine to check them. If all tests passed, the database would be strong consistency. Is that true

Porcupine supports partitioning checking of history, but we haven't used it yet. 

we can provide a feature that likes:

1. record the initialization state in the history
2. record 200 events 
3. pass init state and 200 events to Porcupine to check
4. return to 1 and do again

**Comment by thinhdanggroup** [comment]
@siddontang 

I was trying this feature with request-count=200 and many rounds. But I think we can't confirm that the database is strong consistency. It just means that a particular run of the database was correct, right?

**Comment by siddontang** [comment]
yes, even we can run the Porcupine all the time, we still can't guarantee the database is correct, but we can think the correct probability is high.
